# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Jabber-SimpleSend
version:      0.03
version_from: lib/Jabber/SimpleSend.pm
installdirs:  site
requires:
    LWP:                           0
    Net::Jabber:                   0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
